import { LibraryComponent, LibraryProp } from '~/model/component'

export const components: LibraryComponent[] = [
  {
    id: 'Text',
    name: 'Text',
    icon: 'mdi-text',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'text',
        name: 'Text',
        type: 'text',
        required: false,
        default: 'Lorem Ipsum',
      },
      {
        id: 'type',
        name: 'Type',
        type: 'choice',
        options: [
          'body-1',
          'body-2',
          'h1',
          'h2',
          'h3',
          'h4',
          'h5',
          'h6',
          'subtitle-1',
          'subtitle-2',
          'button',
          'caption',
          'overline',
        ],
        required: false,
        default: 'body-1',
      },
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
    ],
  },
  {
    id: 'VContainer',
    name: 'Grid',
    icon: 'mdi-grid-large',
    toplevel: true,
    children: ['VRow'],
    props: [
      {
        id: 'fluid',
        name: 'Fluid (full width)',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'VRow',
    name: 'Row',
    icon: 'mdi-grid-large',
    toplevel: false,
    children: ['VCol'],
    props: [
      {
        id: 'justify',
        name: 'Justification',
        type: 'choice',
        options: ['start', 'center', 'end', 'space-between', 'space-around'],
        required: false,
        default: undefined,
      },
      {
        id: 'align',
        name: 'Alignment',
        type: 'choice',
        required: false,
        options: ['start', 'center', 'end', 'baseline', 'stretch'],
        default: undefined,
      },
      {
        id: 'align-content',
        name: 'Content alignment',
        type: 'choice',
        options: ['start', 'center', 'end', 'space-between', 'space-around', 'stretch'],
        required: false,
        default: undefined,
      },
      {
        id: 'dense',
        name: 'Dense',
        type: 'boolean',
        default: false,
      },
      {
        id: 'no-gutters',
        name: 'No gutters',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'VCol',
    name: 'Column',
    icon: 'mdi-grid-large',
    toplevel: false,
    children: 'toplevel',
    props: [
      {
        id: 'cols',
        name: 'Columns',
        type: 'cols',
        default: undefined,
      },
      {
        id: 'align-self',
        name: 'Alignment',
        type: 'choice',
        options: ['start', 'center', 'end', 'auto', 'baseline', 'stretch'],
        required: false,
        default: undefined,
      },
    ],
  },
  {
    id: 'VCard',
    name: 'Card',
    icon: 'mdi-card-account-details',
    toplevel: true,
    children: 'toplevel',
    props: [
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
      {
        id: 'title',
        name: 'Title',
        type: 'text',
        required: false,
        default: 'Card title',
      },
      {
        id: 'outlined',
        name: 'Outlined',
        type: 'boolean',
        default: false,
      },
      {
        id: 'elevation',
        name: 'Elevation',
        type: 'slider',
        default: 4,
        min: 0,
        max: 24,
      },
    ],
  },
  {
    id: 'VChip',
    name: 'Chip',
    icon: 'mdi-label',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'size',
        name: 'Size',
        type: 'choice',
        options: ['x-small', 'small', 'regular', 'large', 'x-large'],
        required: true,
        default: 'regular',
      },
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: 'primary',
      },
      {
        id: 'outlined',
        name: 'Outlined',
        type: 'boolean',
        default: false,
      },
      {
        id: 'label',
        name: 'Label',
        type: 'text',
        required: false,
        default: 'Chip label',
      },
      {
        id: 'icon',
        name: 'Icon',
        type: 'icon',
        default: undefined,
        required: false,
      },
    ],
  },
  {
    id: 'VIcon',
    name: 'Icon',
    icon: 'mdi-image-filter-vintage',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'icon',
        name: 'Icon',
        type: 'icon',
        required: true,
        default: undefined,
      },
      {
        id: 'size',
        name: 'Size',
        type: 'choice',
        options: ['x-small', 'small', 'regular', 'large', 'x-large'],
        required: true,
        default: 'regular',
      },
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'VTextField',
    name: 'Text field',
    icon: 'mdi-form-textbox',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
      {
        id: 'label',
        name: 'Label',
        type: 'text',
        required: false,
        default: 'Text field label',
      },
      {
        id: 'value',
        name: 'Value',
        type: 'text',
        required: false,
        default: '',
      },
      {
        id: 'outlined',
        name: 'Outlined',
        type: 'boolean',
        default: false,
      },
      {
        id: 'dense',
        name: 'Dense',
        type: 'boolean',
        default: false,
      },
      {
        id: 'clearable',
        name: 'Clearable',
        type: 'boolean',
        default: false,
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'VSelect',
    name: 'Select',
    icon: 'mdi-form-dropdown',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
      {
        id: 'label',
        name: 'Label',
        type: 'text',
        required: false,
        default: 'Select label',
      },
      {
        id: 'value',
        name: 'Value',
        type: 'text',
        required: false,
        default: '',
      },
      {
        id: 'items',
        name: 'Items',
        type: 'json',
        default: [
          'Alabama',
          'Alaska',
          'American Samoa',
          'Arizona',
          'Arkansas',
          'California',
          'Colorado',
          'Connecticut',
          'Delaware',
          'District of Columbia',
          'Federated States of Micronesia',
          'Florida',
          'Georgia',
          'Guam',
          'Hawaii',
          'Idaho',
          'Illinois',
          'Indiana',
          'Iowa',
          'Kansas',
          'Kentucky',
          'Louisiana',
          'Maine',
          'Marshall Islands',
          'Maryland',
          'Massachusetts',
          'Michigan',
          'Minnesota',
          'Mississippi',
          'Missouri',
          'Montana',
          'Nebraska',
          'Nevada',
          'New Hampshire',
          'New Jersey',
          'New Mexico',
          'New York',
          'North Carolina',
          'North Dakota',
          'Northern Mariana Islands',
          'Ohio',
          'Oklahoma',
          'Oregon',
          'Palau',
          'Pennsylvania',
          'Puerto Rico',
          'Rhode Island',
          'South Carolina',
          'South Dakota',
          'Tennessee',
          'Texas',
          'Utah',
          'Vermont',
          'Virgin Island',
          'Virginia',
          'Washington',
          'West Virginia',
          'Wisconsin',
          'Wyoming',
        ],
      },
      {
        id: 'outlined',
        name: 'Outlined',
        type: 'boolean',
        default: false,
      },
      {
        id: 'dense',
        name: 'Dense',
        type: 'boolean',
        default: false,
      },
      {
        id: 'chips',
        name: 'Chips',
        type: 'boolean',
        default: false,
      },
      {
        id: 'multiple',
        name: 'Multiple',
        type: 'boolean',
        default: false,
      },
      {
        id: 'clearable',
        name: 'Clearable',
        type: 'boolean',
        default: false,
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'VCheckbox',
    name: 'Checkbox',
    icon: 'mdi-checkbox-marked-outline',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
      {
        id: 'label',
        name: 'Label',
        type: 'text',
        required: false,
        default: 'Checkbox label',
      },
      {
        id: 'value',
        name: 'Selected',
        type: 'boolean',
        default: false,
      },
      {
        id: 'dense',
        name: 'Dense',
        type: 'boolean',
        default: false,
      },
      {
        id: 'indeterminate',
        name: 'Three states',
        type: 'boolean',
        default: false,
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'VRadioGroup',
    name: 'Radio group',
    icon: 'mdi-radiobox-marked',
    toplevel: true,
    children: ['VRadio'],
    props: [
      {
        id: 'direction',
        name: 'Direction',
        type: 'choice',
        options: ['row', 'column'],
        required: true,
        default: 'row',
      },
      {
        id: 'selected',
        name: 'Selected',
        type: 'text',
        required: false,
        default: '',
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'VRadio',
    name: 'Radio',
    icon: 'mdi-radiobox-marked',
    toplevel: false,
    children: [],
    props: [
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
      {
        id: 'label',
        name: 'Label',
        type: 'text',
        required: false,
        default: 'Radio label',
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'VSwitch',
    name: 'Switch',
    icon: 'mdi-toggle-switch',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
      {
        id: 'label',
        name: 'Label',
        type: 'text',
        required: false,
        default: 'Switch label',
      },
      {
        id: 'selected',
        name: 'Selected',
        type: 'boolean',
        default: false,
      },
      {
        id: 'dense',
        name: 'Dense',
        type: 'boolean',
        default: false,
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'VSlider',
    name: 'Slider',
    icon: 'mdi-minus',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
      {
        id: 'label',
        name: 'Label',
        type: 'text',
        required: false,
        default: 'Slider label',
      },
      {
        id: 'min',
        name: 'Minimum',
        type: 'integer',
        required: true,
        default: 0,
      },
      {
        id: 'max',
        name: 'Maximum',
        type: 'integer',
        required: true,
        default: 20,
      },
      {
        id: 'value',
        name: 'Value',
        type: 'integer',
        required: true,
        default: 0,
      },
      {
        id: 'outlined',
        name: 'Outlined',
        type: 'boolean',
        default: false,
      },
      {
        id: 'dense',
        name: 'Dense',
        type: 'boolean',
        default: false,
      },
      {
        id: 'clearable',
        name: 'Clearable',
        type: 'boolean',
        default: false,
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'VBtn',
    name: 'Button',
    icon: 'mdi-gesture-tap-button',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'size',
        name: 'Size',
        type: 'choice',
        options: ['x-small', 'small', 'regular', 'large', 'x-large'],
        required: true,
        default: 'regular',
      },
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
      {
        id: 'outlined',
        name: 'Outlined',
        type: 'boolean',
        default: false,
      },
      {
        id: 'label',
        name: 'Label',
        type: 'text',
        required: false,
        default: 'Button label',
      },
      {
        id: 'text',
        name: 'Text only',
        type: 'boolean',
        default: false,
      },
      {
        id: 'iconLeft',
        name: 'Icon left',
        type: 'icon',
        default: undefined,
        required: false,
      },
      {
        id: 'iconRight',
        name: 'Icon right',
        type: 'icon',
        default: undefined,
        required: false,
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
      {
        id: 'elevation',
        name: 'Elevation',
        type: 'slider',
        default: 2,
        min: 0,
        max: 24,
      },
    ],
  },
  {
    id: 'VList',
    name: 'List',
    icon: 'mdi-format-list-bulleted',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'dense',
        name: 'Dense',
        type: 'boolean',
        default: false,
      },
      {
        id: 'color',
        name: 'Color',
        type: 'color',
        required: false,
        default: undefined,
      },
      {
        id: 'items',
        name: 'Items',
        type: 'json',
        default: [
          {
            action: 'mdi-ticket',
            items: [{ title: 'List Item' }],
            title: 'Attractions',
          },
          {
            action: 'mdi-silverware-fork-knife',
            active: true,
            items: [{ title: 'Breakfast & brunch' }, { title: 'New American' }, { title: 'Sushi' }],
            title: 'Dining',
          },
          {
            action: 'mdi-school',
            items: [{ title: 'List Item' }],
            title: 'Education',
          },
          {
            action: 'mdi-run',
            items: [{ title: 'List Item' }],
            title: 'Family',
          },
          {
            action: 'mdi-bottle-tonic-plus',
            items: [{ title: 'List Item' }],
            title: 'Health',
          },
          {
            action: 'mdi-content-cut',
            items: [{ title: 'List Item' }],
            title: 'Office',
          },
          {
            action: 'mdi-tag',
            items: [{ title: 'List Item' }],
            title: 'Promotions',
          },
        ],
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
      {
        id: 'elevation',
        name: 'Elevation',
        type: 'slider',
        default: 2,
        min: 0,
        max: 24,
      },
    ],
  },
  {
    id: 'VTable',
    name: 'Table',
    icon: 'mdi-table',
    toplevel: true,
    children: [],
    props: [
      {
        id: 'caption',
        name: 'Caption',
        type: 'text',
        required: false,
        default: 'Table caoption',
      },
      {
        id: 'dense',
        name: 'Dense',
        type: 'boolean',
        default: false,
      },
      {
        id: 'headers',
        name: 'Headers',
        type: 'json',
        default: [
          { text: 'Dessert (100g serving)', align: 'start', sortable: false, value: 'name' },
          { text: 'Calories', value: 'calories' },
          { text: 'Fat (g)', value: 'fat' },
          { text: 'Carbs (g)', value: 'carbs' },
          { text: 'Protein (g)', value: 'protein' },
          { text: 'Iron (%)', value: 'iron' },
        ],
      },
      {
        id: 'items',
        name: 'Items',
        type: 'json',
        default: [
          { name: 'Frozen Yogurt', calories: 159, fat: 6.0, carbs: 24, protein: 4.0, iron: '1%' },
          {
            name: 'Ice cream sandwich',
            calories: 237,
            fat: 9.0,
            carbs: 37,
            protein: 4.3,
            iron: '1%',
          },
          { name: 'Eclair', calories: 262, fat: 16.0, carbs: 23, protein: 6.0, iron: '7%' },
          { name: 'Cupcake', calories: 305, fat: 3.7, carbs: 67, protein: 4.3, iron: '8%' },
          { name: 'Gingerbread', calories: 356, fat: 16.0, carbs: 49, protein: 3.9, iron: '16%' },
          { name: 'Jelly bean', calories: 375, fat: 0.0, carbs: 94, protein: 0.0, iron: '0%' },
          { name: 'Lollipop', calories: 392, fat: 0.2, carbs: 98, protein: 0, iron: '2%' },
          { name: 'Honeycomb', calories: 408, fat: 3.2, carbs: 87, protein: 6.5, iron: '45%' },
          { name: 'Donut', calories: 452, fat: 25.0, carbs: 51, protein: 4.9, iron: '22%' },
          { name: 'KitKat', calories: 518, fat: 26.0, carbs: 65, protein: 7, iron: '6%' },
        ],
      },
      {
        id: 'disabled',
        name: 'Disabled',
        type: 'boolean',
        default: false,
      },
    ],
  },
]

const marginsPaddings: LibraryProp[] = [
  { id: 'mt', section: 'Margins', name: 'top', type: 'margin-y', default: undefined },
  { id: 'mb', name: 'bottom', type: 'margin-y', default: undefined },
  { id: 'ml', name: 'left', type: 'margin-x', default: undefined },
  { id: 'mr', name: 'right', type: 'margin-x', default: undefined },
  { id: 'pt', section: 'Paddings', name: 'top', type: 'padding', default: undefined },
  { id: 'pb', name: 'bottom', type: 'padding', default: undefined },
  { id: 'pl', name: 'left', type: 'padding', default: undefined },
  { id: 'pr', name: 'right', type: 'padding', default: undefined },
]

components.forEach(component => {
  marginsPaddings.forEach(prop => component.props.push(prop))
})

export function getComponentById(id: string): LibraryComponent {
  const component = components.find(candidate => candidate.id === id)
  if (!component) {
    throw new Error(`Unknown library component '${id}`)
  }

  return component
}

export function getPermittedComponents(container: LibraryComponent | null): LibraryComponent[] {
  if (container && container.children !== 'toplevel') {
    return container.children.map(childId => getComponentById(childId))
  }
  return components.filter(component => component.toplevel)
}
